# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn test --file pom.xml 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel && pip install requests
    
    - name: Upload test results
      run:  python upload-test-results.py --file TEST-com.mkyong.examples.TestMessageBuilder.xml --org test-hub --project java-maven-junit-helloworld  --build $GITHUB_RUN_NUMBER --coverage jacoco.xml --branch $GITHUB_REF
